### ISSUE TITLE
Suggestion to provide examples of using Java to send JSON-RPC API calls to Ethereum node

### ISSUE THREAD

**Issue by 0xRadix** [awsdocs/amazon-managed-blockchain-ethereum-developer-guide#1]
Figured this may be helpful to add, and something that I am trying to figure out on my own. A very simple example could be something as follows:

```
HttpService httpService = new HttpService("NODE_HTTP_ENDPOINT_HERE");
Web3j web3 = Web3j.build(httpService);
try {
  Web3ClientVersion clientVersion = web3.web3ClientVersion().send();
} catch (IOException e) {
  throw new RuntimeException(e.getMessage());
}
```

Of course, there may be more that needs to be done to approach this correctly when using API keys, but open to feedback on this. Please do feel free to correct me if I have the wrong idea as I am new to working with the AWS SDK, and Web3.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
